name: Continuous integration
on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  RUSTUP_MAX_RETRIES: 10

jobs:
  fmt-clippy:
    name: Check Formating & Lints
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust:
          - stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3..5.0

      - name: Cargo Cache
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cache

      - name: Install Rustup
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: default
          default: true

      - name: Rustfmt
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo fmt
          args: --all -- --check

      - name: Clippy
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo clippy
          args: --workspace -- -D warnings

  tests:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust:
          - stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3..5.0

      - name: Cargo Cache
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cache

      - name: Install Rustup
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: default
          default: true

      - name: Install nextest
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo install
          args: cargo-nextest

      - name: Test
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo nextest
          args: run --workspace --bins --lib --tests --examples --no-fail-fast
